version: '3.8'
services:
  master:
    build: .
    hostname: master
    environment:
      - ROLE=master
      - PVM_ALLOW_ROOT=1
    networks:
      - pvmnet
    tty: true
  worker:
    build: .
    hostname: worker
    environment:
      - ROLE=worker
      - PVM_ALLOW_ROOT=1
    networks:
      - pvmnet
    tty: true
    depends_on:
      - master
networks:
  pvmnet:
    driver: bridge
