version: '3.8'
services:
  master:
    build: .
    environment:
      - ROLE=master
      - PVM_ALLOW_ROOT=1
    networks:
      - pvmnet
    tty: true
  worker:
    build: .
    environment:
      - ROLE=worker
      - PVM_ALLOW_ROOT=1
    networks:
      - pvmnet
    tty: true
    depends_on:
      - master
    deploy:
      replicas: 7
networks:
  pvmnet:
    driver: bridge
